{
 "title": "Druid DataSource",
 "description": "Druid DataSource Dashboard",
 "tags": [
  "druid",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(druid_initial_size, application)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(druid_initial_size{application=\"$application\"}, region)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(druid_initial_size{application=\"$application\", region=~\"$region\"}, instance)"
   },
   {
    "name": "druid_pool_name",
    "label": "Druid Pool Name",
    "query": "label_values(druid_initial_size{application=\"$application\", region=~\"$region\", instance=~\"$instance\"}, pool)"
   },
   {
    "name": "sql",
    "query": "label_values(druid_sql_execute_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\"}, sql)"
   },
   {
    "name": "uri",
    "query": "label_values(druid_uri_request_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\"}, uri)"
   }
  ]
 },
 "panels": [
  { "title": "DataSource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Size ${instance}",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_initial_size{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}",
     "legendFormat": "InitialSize"
    },
    {
     "expr": "druid_active_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}",
     "legendFormat": "ActiveCount"
    },
    {
     "expr": "druid_pooling_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}",
     "legendFormat": "PoolingCount"
    },
    {
     "expr": "druid_min_idle{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}",
     "legendFormat": "MinIdle"
    },
    {
     "expr": "druid_max_active{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}",
     "legendFormat": "maxActive"
    }
   ]
  },
  {
   "title": "PoolingPeak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_pooling_peak{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "ActivePeak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_active_peak{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "连接持有时间分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_connection_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"1ms\"}) ",
     "legendFormat": "1ms"
    },
    {
     "expr": "sum(druid_connection_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"10ms\"}) ",
     "legendFormat": "10ms"
    },
    {
     "expr": "sum(druid_connection_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"100ms\"}) ",
     "legendFormat": "100ms"
    },
    {
     "expr": "sum(druid_connection_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"1s\"}) ",
     "legendFormat": "1s"
    },
    {
     "expr": "sum(druid_connection_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"10s\"}) ",
     "legendFormat": "10s"
    },
    {
     "expr": "sum(druid_connection_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"100s\"}) ",
     "legendFormat": "100s"
    },
    {
     "expr": "sum(druid_connection_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"Inf\"}) ",
     "legendFormat": "Inf"
    }
   ]
  },
  {
   "title": "ExecuteCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_execute_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "ExecuteQueryCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_execute_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "ExecuteUpdateCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_execute_update_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "ExecuteBatchCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_execute_batch_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "CommitCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_commit_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "RollbackCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_rollback_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "ErrorCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_error_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "事务时间分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_transaction_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"1ms\"})",
     "legendFormat": "1ms"
    },
    {
     "expr": "sum(druid_transaction_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"10ms\"})",
     "legendFormat": "10ms"
    },
    {
     "expr": "sum(druid_transaction_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"100ms\"})",
     "legendFormat": "100ms"
    },
    {
     "expr": "sum(druid_transaction_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"1s\"})",
     "legendFormat": "1s"
    },
    {
     "expr": "sum(druid_transaction_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"10s\"})",
     "legendFormat": "10s"
    },
    {
     "expr": "sum(druid_transaction_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"100s\"})",
     "legendFormat": "100s"
    },
    {
     "expr": "sum(druid_transaction_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", le=\"Inf\"})",
     "legendFormat": "Inf"
    }
   ]
  },
  {
   "title": "MaxWaitThreadCount",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_max_wait_thread_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "累计等待时长",
   "type": "singlestat",
   "description": "获取连接时累计等待多长时间",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 25 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_not_empty_wait_millis{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "累计等待次数",
   "type": "singlestat",
   "description": "获取连接时累计等待多少次",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_not_empty_wait_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "查询超时时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_query_timeout{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "事务查询超时时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(druid_transaction_query_timeout{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"})"
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL 执行中",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_sql_running_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}) without (instance))",
       "legendFormat": "{{sql}}"
      }
     ]
    },
    {
     "title": "SQL 最大并发",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_sql_concurrent_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}) without (instance))",
       "legendFormat": "{{sql}}"
      }
     ]
    },
    {
     "title": "SQL 执行数",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_sql_execute_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}) without (instance))",
       "legendFormat": "{{sql}}"
      }
     ]
    },
    {
     "title": "SQL 错误数",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_sql_error_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}) without (instance))",
       "legendFormat": "{{sql}}"
      }
     ]
    },
    {
     "title": "SQL 执行时间",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_sql_total_time{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}) without (instance))",
       "legendFormat": "{{sql}}"
      }
     ]
    },
    {
     "title": "SQL 最慢 (max)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(max(druid_sql_max_timespan{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\"}) without (instance))",
       "legendFormat": "{{sql}}"
      }
     ]
    }
   ]
  },
  {
   "title": "URI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求中",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_uri_running_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "请求次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_uri_request_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "请求时间（和）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_uri_request_time_millis{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "最慢 (max)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(max(druid_uri_request_time_millis_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "最大并发",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_uri_concurrent_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Jdbc执行数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_uri_jdbc_execute_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Jdbc时间",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_uri_jdbc_execute_time_millis{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Jdbc出错数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(druid_uri_jdbc_execute_error_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"}) without (instance))",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL: $sql",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "sql",
   "collapsed": true,
   "panels": [
    {
     "title": "执行中",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_sql_running_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})"
      }
     ]
    },
    {
     "title": "最大并发",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_sql_concurrent_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})"
      }
     ]
    },
    {
     "title": "执行数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_sql_execute_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})"
      }
     ]
    },
    {
     "title": "读取行数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_sql_fetch_row_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})"
      }
     ]
    },
    {
     "title": "执行时间",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_sql_total_time{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})"
      }
     ]
    },
    {
     "title": "最慢",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(druid_sql_max_timespan{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})"
      }
     ]
    },
    {
     "title": "错误数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_sql_error_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})"
      }
     ]
    },
    {
     "title": "Last Error",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(druid_sql_last_error_time{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"})",
       "legendFormat": "{{$sql_err_msg}} "
      }
     ]
    },
    {
     "title": "执行时间分布",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(druid_sql_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"1ms\"})",
       "legendFormat": "1ms"
      },
      {
       "expr": "sum(druid_sql_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10ms\"})",
       "legendFormat": "10ms"
      },
      {
       "expr": "sum(druid_sql_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100ms\"})",
       "legendFormat": "100ms"
      },
      {
       "expr": "sum(druid_sql_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"1s\"})",
       "legendFormat": "1s"
      },
      {
       "expr": "sum(druid_sql_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10s\"})",
       "legendFormat": "10s"
      },
      {
       "expr": "sum(druid_sql_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100s\"})",
       "legendFormat": "100s"
      },
      {
       "expr": "sum(druid_sql_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"Inf\"})",
       "legendFormat": "Inf"
      }
     ]
    },
    {
     "title": "执行+RS分布",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(druid_sql_execute_and_result_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"1ms\"})",
       "legendFormat": "1ms"
      },
      {
       "expr": "sum(druid_sql_execute_and_result_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10ms\"})",
       "legendFormat": "10ms"
      },
      {
       "expr": "sum(druid_sql_execute_and_result_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10ms\"})",
       "legendFormat": "100ms"
      },
      {
       "expr": "sum(druid_sql_execute_and_result_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100ms\"})",
       "legendFormat": "1s"
      },
      {
       "expr": "sum(druid_sql_execute_and_result_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10s\"})",
       "legendFormat": "10s"
      },
      {
       "expr": "sum(druid_sql_execute_and_result_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100s\"})",
       "legendFormat": "100s"
      },
      {
       "expr": "sum(druid_sql_execute_and_result_hold_time_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"Inf\"})",
       "legendFormat": "Inf"
      }
     ]
    },
    {
     "title": "读取行时间分布",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(druid_sql_fetch_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"1ms\"})",
       "legendFormat": "1ms"
      },
      {
       "expr": "sum(druid_sql_fetch_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10ms\"})",
       "legendFormat": "10ms"
      },
      {
       "expr": "sum(druid_sql_fetch_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100ms\"})",
       "legendFormat": "100ms"
      },
      {
       "expr": "sum(druid_sql_fetch_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"1s\"})",
       "legendFormat": "1s"
      },
      {
       "expr": "sum(druid_sql_fetch_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10s\"})",
       "legendFormat": "10s"
      },
      {
       "expr": "sum(druid_sql_fetch_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100s\"})",
       "legendFormat": "100s"
      },
      {
       "expr": "sum(druid_sql_fetch_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"Inf\"})",
       "legendFormat": "Inf"
      }
     ]
    },
    {
     "title": "更新行时间分布",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(druid_sql_effected_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"1ms\"})",
       "legendFormat": "1ms"
      },
      {
       "expr": "sum(druid_sql_effected_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10ms\"})",
       "legendFormat": "10ms"
      },
      {
       "expr": "sum(druid_sql_effected_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100ms\"})",
       "legendFormat": "100ms"
      },
      {
       "expr": "sum(druid_sql_effected_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"1s\"})",
       "legendFormat": "1s"
      },
      {
       "expr": "sum(druid_sql_effected_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"10s\"})",
       "legendFormat": "10s"
      },
      {
       "expr": "sum(druid_sql_effected_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"100s\"})",
       "legendFormat": "100s"
      },
      {
       "expr": "sum(druid_sql_effected_row_count_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\", le=\"Inf\"})",
       "legendFormat": "Inf"
      }
     ]
    },
    {
     "title": "Last Error Message",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "max(druid_sql_last_error_time{application=\"$application\", region=~\"$region\", instance=~\"$instance\", pool=~\"$druid_pool_name\", sql=~\"$sql\"}) by (class,message)",
       "legendFormat": "{{class}}<br/><br/>{{message}} "
      }
     ]
    }
   ]
  },
  {
   "title": "URI: $uri",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "uri",
   "collapsed": true,
   "panels": [
    {
     "title": "请求中",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_uri_running_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    },
    {
     "title": "请求次数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_uri_request_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    },
    {
     "title": "请求时间（和）",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_uri_request_time_millis{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    },
    {
     "title": "请求最慢",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(druid_uri_request_time_millis_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    },
    {
     "title": "执行时间分布",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(druid_uri_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\", le=\"1ms\"})",
       "legendFormat": "1ms"
      },
      {
       "expr": "sum(druid_uri_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\", le=\"10ms\"})",
       "legendFormat": "10ms"
      },
      {
       "expr": "sum(druid_uri_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\", le=\"100ms\"})",
       "legendFormat": "100ms"
      },
      {
       "expr": "sum(druid_uri_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\", le=\"1s\"})",
       "legendFormat": "1s"
      },
      {
       "expr": "sum(druid_uri_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\", le=\"10s\"})",
       "legendFormat": "10s"
      },
      {
       "expr": "sum(druid_uri_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\", le=\"100s\"})",
       "legendFormat": "100s"
      },
      {
       "expr": "sum(druid_uri_histogram_bucket{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\", le=\"Inf\"})",
       "legendFormat": "Inf"
      }
     ]
    },
    {
     "title": "最大并发",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_uri_concurrent_max{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    },
    {
     "title": "Jdbc执行数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_uri_jdbc_execute_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    },
    {
     "title": "Jdbc时间",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_uri_jdbc_execute_time_millis{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    },
    {
     "title": "Jdbc出错数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(druid_uri_jdbc_execute_error_count{application=\"$application\", region=~\"$region\", instance=~\"$instance\", uri=~\"$uri\"})"
      }
     ]
    }
   ]
  }
 ]
}